CREATE DATABASE IF NOT EXISTS db_apt01
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;


USE db_apt01;


CREATE TABLE TB_LISTA_SEXO_BIOLOGICO (
	N_ID_LISTA_SEXO_BIOLOGICO INT NOT NULL AUTO_INCREMENT,
	S_LISTA_SEXO_BIOLOGICO VARCHAR(15) NOT NULL,
	PRIMARY KEY (N_ID_LISTA_SEXO_BIOLOGICO)
);
